version: "3.7"

services:
  backend:
    container_name: backend-fernec
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - fernet

  frontend:
    container_name: frontend-fernec
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      BACK_URL: "http://backend:8000"
    ports:
      - "3000:3000"
    networks:
      - fernet

networks:
  fernet:
    name: fernet
