host: 0.0.0.0
port: 8000
log_level: "INFO"
cnn_path: "./cotatest.keras"
rnn_path: "./cotatest_rnn_4.keras"
cnn_binary_path: "./vgg16_eche_4.keras"
rnn_binary_path: "./eche_rnn_binary_3.keras"
video_config:
  HEIGHT: 112
  WIDTH: 112
  CHANNELS: 3
  MAX_SEQ_LENGTH: 10
  NUM_FEATURES: 1024
  FRAMES_ORDER_MAGNITUDE: 5
  FACE_BATCH_SIZE: 20
email_config:
  EMAIL_SENDER: "fernec.fiuba@gmail.com"
  EMAIL_PASSWORD: "fake_password"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: 465
